### ISSUE TITLE
Provide API for inspecting the backend data

### ISSUE THREAD

**Issue by robacarp** [mosquito-cr/mosquito#90]
Currently inspecting the backend data requires querying the backend directly. It would be nice to be able to ask mosquito's backend for data about:

- [x] The current list of queues (#153)
- [x] The current list of job runs (#153)
- [x] A list of active ~~runners~~ overseers (#150)
- [ ] Statistics about a runner
  - [ ] How many tasks have been finished in the last hour,minute,second (#156)
  - [ ] How many tasks have succeed or failed in the last <span> (#156)
- [ ] How many tasks have been _enqueued_ in the last hour/minute/second (#155)
- [x] What a runner is currently doing (#147)
- [ ] JobRuns that have recently failed or succeeded
  - [x] The parameters given to a job run (#148)
  - [ ] when it was started (#157)
  - [ ] how long it took to run (#157)

~~Prototyping for these features is being monkeypatched in the [TUI Visualizer](https://github.com/mosquito-cr/tui-visualizer) project.~~

**Comment by robacarp** [comment]
Closing in favor of milestone
